// The contract between the engine and the UI. The engine owns this file; the UI only imports it.

export type Destination = "SG" | "JP";

export type DegreeLevel = "none" | "diploma" | "bachelor" | "master" | "doctorate";

export type LanguageLevel = "basic" | "conversational" | "business" | "native";

export interface Profile {
  /** ISO 3166-1 alpha-2 codes, one or two, e.g. ["IN"] or ["ID", "AU"] */
  nationalities: string[];
  age: number;
  degree: DegreeLevel;
  university?: string;
  graduationYear?: number;
  field?: string;
  yearsExperience: number;
  /** ISO 639-1 code, e.g. "en" or "ja" */
  languages: { code: string; level: LanguageLevel }[];
  /** SGD per month for SG, JPY per year for JP */
  expectedSalary?: Partial<Record<Destination, number>>;
  /**
   * Whether they already have a job offer. Nothing evaluates this: it decides which routes are worth
   * reading first, because six of the ten need an employer to apply and those are unreachable
   * without one.
   */
  hasOffer?: boolean;
  /**
   * ISO 3166-1 alpha-2 country of the university, when there is one. Collected but not yet
   * evaluated. It is the missing fact behind `sg-work-holiday-pass#university-country`, which turns
   * on where the university is rather than on nationality, and which stays `manual` until a rule
   * kind can read this.
   */
  universityCountry?: string;
}

export type RouteStatus = "open" | "depends" | "closed";

/** Who has to check or prove a requirement. */
export type Checker = "you" | "employer" | "authority";

/** Whether a requirement is met for this profile, as far as the engine can tell. */
export type Outcome = "met" | "unmet" | "unknown";

export interface Source {
  url: string;
  publisher: string;
  /** YYYY-MM-DD */
  retrievedOn: string;
  /** Verbatim excerpt from the page, in the language the page is written in. */
  quote: string;
  /**
   * Unofficial literal English rendering, present whenever `quote` is not in English. Show it under
   * the quote, labelled as unofficial, never in place of it. Most Japan routes are sourced from
   * Japanese pages, so without this the route pages are unreadable to an English-speaking reader.
   */
  translation?: string | undefined;
}

export interface ChecklistItem {
  requirementId: string;
  /** One plain-English sentence. */
  text: string;
  who: Checker;
  outcome: Outcome;
  /** Optional sentence specific to this profile. */
  note?: string;
  sources: Source[];
}

export interface RouteResult {
  routeId: string;
  destination: Destination;
  name: string;
  status: RouteStatus;
  /** One sentence explaining the status for this profile. */
  reason: string;
  checklist: ChecklistItem[];
  /** Dated rule changes that affect this route, e.g. a salary floor rising next January. */
  upcomingChanges: { on: string; text: string }[];
  /** YYYY-MM-DD, or null until a person has verified every requirement against its sources. */
  verifiedOn: string | null;
  /**
   * True when an employer has to apply on your behalf. Structural rather than a rule: it is what
   * separates the routes you can pursue alone from the ones that need an offer first.
   */
  requiresEmployer: boolean;
}

/** One requirement an insight was derived from, so a reader can check the reasoning. */
export interface InsightFrom {
  routeId: string;
  routeName: string;
  requirementId: string;
  /** The requirement's own sentence, unchanged. */
  requirementText: string;
  sources: Source[];
}

export type InsightKind = "salary-floor-change" | "employer-size";

/**
 * What the rules mean for this person, computed from the rules themselves.
 *
 * Every insight is a function of the route data and the profile. Nothing here is generated by a
 * model, and `from` is never empty: an insight that cannot cite the requirements behind it is a
 * guess, and not guessing is the site's only advantage over a forum. Show `text` with `from`
 * reachable beside it.
 */
export interface Insight {
  id: string;
  kind: InsightKind;
  text: string;
  from: InsightFrom[];
}

export interface DestinationResult {
  destination: Destination;
  name: string;
  routes: RouteResult[];
  /** May be empty. Ordered by how much they are worth reading. */
  insights: Insight[];
}

export interface RouteSummary {
  routeId: string;
  destination: Destination;
  name: string;
  summary: string;
  verifiedOn: string | null;
}

export interface RequirementView {
  id: string;
  text: string;
  who: Checker;
  sources: Source[];
  /** YYYY-MM-DD bounds, when the requirement only applies for part of the time. */
  effective?: { from?: string; to?: string };
}

export interface RouteDetail extends RouteSummary {
  officialUrl: string;
  requirements: RequirementView[];
}
